name: bnv_opendata
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Dart
  dartx: 1.1.0
  auto_size_text: 3.0.0

  #Favourite library
  provider: 6.0.3
  flutter_bloc: 8.1.1
  google_fonts: any
  url_launcher: ^6.3.2
  path_provider: 2.0.11
  webview_flutter: 4.13.0
  shared_preferences: 2.0.15
  font_awesome_flutter: 10.1.0
  lint: 1.10.0
  table_calendar: ^3.1.3
  image_picker: ^1.0.8
  flutter_svg: 1.1.4

  #Library helpful
  intl: ^0.20.2
  event_bus: 2.0.0
  equatable: 2.0.3
  fluttertoast: ^8.2.4
  json_annotation: ^4.9.0
  flutter_screenutil: 5.5.3+2
  cached_network_image: 3.2.1
  smooth_page_indicator: 1.0.0+2
  flutter_staggered_grid_view: 0.6.2
  rxdart: 0.27.5
  get: 4.7.2
  injectable: ^2.5.2
  freezed: ^3.2.3
  connectivity_plus: ^6.0.0
  analyzer: any
  retrofit: ^4.9.0
  logger: any  #for logging purpose
  pretty_dio_logger: ^1.2.0-beta-1

  # Library support for app
  crypto: 3.0.2
  sqflite: ^2.3.3
  flutter_secure_storage: ^9.2.4
  get_it: ^7.2.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^10.1.2 #'>=4.0.0 <5.0.0'
  build_runner: ^2.10.1 #flutter pub run build_runner build --delete-conflicting-outputs
  json_serializable: '>4.4.0'
  injectable_generator: ^2.9.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/font/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/font/nunitosansregular.ttf
        - asset: assets/font/nunitosansblack.ttf
          weight: 900
        - asset: assets/font/nunitosansbold.ttf
          weight: 800
        - asset: assets/font/nunitosanssemibold.ttf
          weight: 700

flutter_intl:
  enabled: true